// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-licenses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_licenses_default = defineTool({
  name: "list_my_licenses",
  title: "List my licence keys",
  description: "List the Code Base licence keys assigned to the signed-in user (key, plan, status, expiry).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("license_keys").select("key, plan, status, activated_at, expires_at, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { licenses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-trades.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_trades_default = defineTool2({
  name: "list_my_trades",
  title: "List my recent trades",
  description: "List the signed-in user's recent trades logged by the Code Base bot / EA.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max trades to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("trades").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trades: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-signals.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_signals_default = defineTool3({
  name: "list_my_signals",
  title: "List my recent trading signals",
  description: "List the signed-in user's most recent AI-generated trading signals (symbol, direction, confidence, prices).",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20).describe("Max signals to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("signals").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { signals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/account-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var account_summary_default = defineTool4({
  name: "get_account_summary",
  title: "Get my Code Base account summary",
  description: "Return the signed-in user's profile, connected MetaTrader accounts, bot configs, and counts of licences/trades/signals.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const uid = ctx.getUserId();
    const [profile, mtAccounts, botConfigs, licenses, trades, signals] = await Promise.all([
      sb.from("profiles").select("*").eq("user_id", uid).maybeSingle(),
      sb.from("mt_accounts").select("id, broker, server, account_number, platform, is_active").eq("user_id", uid),
      sb.from("bot_configs").select("*").eq("user_id", uid),
      sb.from("license_keys").select("id", { count: "exact", head: true }).eq("user_id", uid),
      sb.from("trades").select("id", { count: "exact", head: true }).eq("user_id", uid),
      sb.from("signals").select("id", { count: "exact", head: true }).eq("user_id", uid)
    ]);
    const summary = {
      user: { id: uid, email: ctx.getUserEmail() },
      profile: profile.data ?? null,
      mt_accounts: mtAccounts.data ?? [],
      bot_configs: botConfigs.data ?? [],
      counts: {
        licenses: licenses.count ?? 0,
        trades: trades.count ?? 0,
        signals: signals.count ?? 0
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vdjckpwwqqcqavrucndh";
var mcp_default = defineMcp({
  name: "code-base-mcp",
  title: "Code Base",
  version: "0.1.0",
  instructions: "Tools for the Code Base copy-trading app. Read the signed-in user's licence keys, connected MetaTrader accounts, bot configurations, recent AI trading signals, and recent trades.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [account_summary_default, list_licenses_default, list_trades_default, list_signals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
